/**
 *
 * $Id$
 */
package minerv1.validation;

import minerv1.Event;

/**
 * A sample validator interface for {@link minerv1.EventDependency}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EventDependencyValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateEvent(Event value);
}
